CREATE SCHEMA IF NOT EXISTS crawler;

SET NAMES 'UTF8MB4';
SET TIME_ZONE = '+3:00';

USE crawler;

DROP TABLE IF EXISTS source;

CREATE TABLE `source`
(
    id        BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    url       VARCHAR(255) NOT NULL,
    schedule  VARCHAR(255) DEFAULT NULL,
    selectors JSON DEFAULT NULL,
    CONSTRAINT UQ_Source_Url UNIQUE (url)
);

DROP TABLE IF EXISTS news_article;

CREATE TABLE `news_article`
(
    id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    source_id    BIGINT UNSIGNED NOT NULL,
    title        VARCHAR(255) DEFAULT NULL,
    content      TEXT DEFAULT NULL,
    publish_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    hash         VARCHAR(255),
    FOREIGN KEY (source_id) REFERENCES source (id), # ON UPDATE/DELETE CASCADE
    CONSTRAINT UQ_News_article_Hash UNIQUE (hash)
);